name: sample azure build and deploy
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Set up Sbt
        uses: Jtalk/setup-sbt@v2
        with:
          version: 1.7.2
      - name: sbt compile
        run: sbt compile

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: target/

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - uses: actions/checkout@v3

      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ./path/to/deploy-input

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd 
          