name: Build sample 
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Set up Sbt
        uses: Jtalk/setup-sbt@v2
        with:
          version: 1.7.2
      - name: sbt compile
        run: sbt compile
