name: Build sample Self Hosted
on:
  workflow_dispatch:
      inputs:
        runners:
          type: choice
          description: self-hosted-runners
          options: 
            - '"self-hosted"'
            - '[ "self-hosted", "DOCKER_SAMPLE_SBT" ]'
        commit_no:
          type: string
          default: ""
          required: false
          description: CommitNo

jobs:
  build:
    runs-on: ${{ fromJSON(github.event.inputs.runners) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: bash ./.github/build.sh

      - name: Deploy
        run: bash ./.github/deploy.sh
