name: Build sample Self Hosted
on:
  workflow_dispatch:
      inputs:
        runners:
          type: choice
          description: self-hosted-runners
          options: 
            - '"self-hosted"'
            - '[ "self-hosted", "DOCKER_TEST" ]'
            - '[ "self-hosted", "KOUTOKU_WSL_PART2" ]'
            - '[ "self-hosted", "KOUTOKU_WSL2" ]'
        buildno:
          type: string
          default: ""
          required: false
          description: build-no
    
jobs:
  build:
    runs-on: ${{ fromJSON(github.event.inputs.runners) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git checkout ${{ github.event.inputs.buildno }}
        if: ${{ github.event.inputs.buildno != '' }}

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Sbt
        uses: Jtalk/setup-sbt@v2
        with:
          version: 1.7.2

      - name: Build
        run: bash ./.github/build.sh

      - name: Deploy
        run: bash ./.github/deploy.sh
