name: Build sample Self Hosted
on:
  workflow_dispatch:
      inputs:
        runners:
          type: choice
          description: self-hosted-runners
          options: 
            - '"self-hosted"'
            - '[ "self-hosted", "DOCKER_SAMPLE_SBT" ]'
        commit_no:
          type: string
          default: ""
          required: false
          description: コミット番号

jobs:
  build:
    runs-on: ${{ fromJSON(github.event.inputs.runners) }}apt
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git checkout ${{ github.event.inputs.commit_no }}
        if: ${{ github.event.inputs.commit_no != '' }}

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Sbt
        uses: Jtalk/setup-sbt@v2
        with:
          version: 1.7.2

      - name: Build
        run: bash ./.github/build.sh

      - name: Deploy
        run: bash ./.github/deploy.sh
